travis:
  secure:
    BINSTAR_TOKEN: nEoofAViGyCadEwACb3K3YmFB2qe89nZT+M4n7sgXLaHuEnwsyX9wlvmubPWlucvJO7uXTdMbDkr4ylN09vPR8YJO2kGWdUTedABAqDo+CC/O6XPLcjaTFbIDHT8MiCJwUHLik2mcwAOThm3om7kGuTGBxMgwF4F1GAGzsPox1JWyosLX4aElgmP/ltzxyDC9gBG/srXm1c8sAyAQDoTONJFAZureJpUKlX8dUIS8aB9EO4nDB2Uh/U1GlgpnJnqYVTu803HlwgW3SEoYPTzUzR9ZhwY0k8QX5pJA9At6i5B641pgLFt7tJIg29HneoJl39TQGAzFm9FIYJt0YGMkJnsRJNdQuH7VfRxSNuwQ9sgErZvaRzfoPQRLNdTspX1/4k9+/lY+RDVkTN7tT2e57PmOX81oN2zOdT+O0KqvABWRHc5EI0mKRVsW/0oIBMr0ZczwjyXDWz03fHM6JWtGNB/E5H8FPlQNvGmW+FS9lD3Yzm9Ignt37MdQgreE4XQxpJTBUMkOalSuaCZq0idrGRCiuNg98nomjGuMedZJBgaHd6QhVPAQo1+bI2Qk/x5JaGXmtK4xvnGtrd22lU+K8wbTG2OoFLIgaIw02tk94dQof9wQenfLiTJeBKAHL5J8BVebhsYWE33X5KTUBGQOTrYUrUCU00vn8tEYlhZzVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
