travis:
  secure:
    BINSTAR_TOKEN: fNZiRX5zKM+G3h4RKwJ3DP0XHDIjtDty9JkVBG5bhe/xFdLSZKfVHGvpMOhmWGx4FwlpJagEBN+tP0oDIVzCPFDUrYeg9m4A+dYksAnIO5iFhgkMBDzVYD/ViPXUQq5B5uVQBZb8K1FX9EYusA5CA8+5OIjOWn+aVPFzgNAmk8scJqqLDBoTh0hKmuyPpOS4rJWE2ptAO9c7e/6MXrfIL+MbAAiFsoAbQihlOhXiUBnNDSWDVW5NOYDcWLBxjgd6UcmQH022g4SuKk/nQ3Lzq3CCRcjHxy4NcQVhL0B56kG8Ink3Ezllau9NwSqrXjiCZU9QoDsOy2jobmAFJ/MtJd+G9k3prhTdXvzv1XhWTngw5KGCy1N1xmJtr+p93kcVFwNCyXFnyn7/AWyOFqIDbj9edRDYPuz8IkawzIyXfSXmvjCK7A62eoxRGUPmvw3Jowf2vM5Y3rzivjfwk/5XYwCoLV4htVaYWlyEkXrAJa/9HuuBKzBIeiwesFsY2jZwyACAtSQdLdDhCn7SLmqApXUgJ7VzI+aaJ87CG6rqmnmNYjFdXIsNP61xrqvQVnY/bAeToOPZs3st3wCfujEv0K40HRtZ/8a6p7asGDuC0SKT1koSNfNMqwOnM8h4p7wjXYAvOwWAqDyZ2p3ECNj4LLAPR93qh1yTOugwBn3oyUE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
